<!---- 
Este archivo es para NETLIFY. CÃ³pialo al fichero build en Netlify como:
File: netlify.toml
----->

[build]
  command = "npm install"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-inline-functions-env"
